import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, EDITOR, MANAGER, SUPER_ADMIN } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'homes',
        path: '',
        title: 'Homes',
        menu_id: ["1","2","3","4","5","25","26","32","56","57"],
        purpose:["create","read","edit","delete"],
        translateKey: 'nav.home',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [SUPER_ADMIN,ADMIN,MANAGER,EDITOR],
        subMenu: [
            {
                key: 'homes.dashboard',
                menu_id: "1",
                purpose: ["read"],
                path: `${APP_PREFIX_PATH}/dashboard`,
                title: 'Home',
                translateKey: 'nav.appsHomes.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [SUPER_ADMIN,ADMIN,MANAGER,EDITOR],
                subMenu: [],
            },
            {
                key: 'homes.categories',
                path: '',
                menu_id: ["25"],
                purpose: ["read"],
                title: 'Categories',
                translateKey: 'nav.appsHomes.categories',
                icon: 'categories',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [SUPER_ADMIN,ADMIN],
                subMenu: [
                    {
                        key: 'categories.categories',
                        menu_id: ["25"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/categories/category-list`,
                        title: 'Category',
                        translateKey: 'nav.categories.category-list',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'categories.category-create',
                        menu_id: ["25"],
                        purpose: ["create"],
                        path: `${APP_PREFIX_PATH}/categories/category-new`,
                        title: 'Create Category',
                        translateKey: 'nav.categories.category-create',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'categories.subcategories',
                        menu_id: ["26"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/subcategories/sub-category-list`,
                        title: 'Sub Category',
                        translateKey: 'nav.categories.sub-category-list',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN],
                        subMenu: [],
                    },
                ],
            },

            {
                key: 'homes.contents',
                menu_id: ["2"],
                purpose: ["read"],
                path: ``,
                title: 'Home',
                translateKey: 'nav.appsHomes.contents',
                icon: 'content',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [SUPER_ADMIN,ADMIN,MANAGER],
                subMenu: [
                    {
                        key: 'contents.liveChannel',
                        menu_id: ["3"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/contents/live-channel-list`,
                        title: 'Live/Linear Channel',
                        translateKey: 'nav.contents.liveChannel',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'contents.vod',
                        menu_id: ["4"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/contents/vod-list`,
                        title: 'VOD Contents',
                        translateKey: 'nav.contents.vod',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN,MANAGER],
                        subMenu: [],
                    },
                    {
                        key: 'contents.featured',
                        menu_id: ["27"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/contents/featured-list`,
                        title: 'FeaturedOld Contents',
                        translateKey: 'nav.contents.featured',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN,MANAGER],
                        subMenu: [],
                    },
                ],
            },

            {
                key: 'homes.webSeries',
                path: '',
                menu_id: ["58"],
                purpose: ["read"],
                title: 'Web Series',
                translateKey: 'nav.appsHomes.webSeries',
                icon: 'webSeries',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [SUPER_ADMIN,ADMIN],
                subMenu: [
                    {
                        key: 'webSeries.webSeries',
                        menu_id: ["58"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/webSeries/webSeries-list`,
                        title: 'Web Series',
                        translateKey: 'nav.webSeries.webSeries-list',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'webSeries.webSeries-create',
                        menu_id: ["58"],
                        purpose: ["create"],
                        path: `${APP_PREFIX_PATH}/webSeries/webSeries-new`,
                        title: 'Create Web Series',
                        translateKey: 'nav.webSeries.webSeries-create',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN],
                        subMenu: [],
                    },
                ],
            },

            {
                key: 'homes.interest',
                path: '',
                menu_id: ["32"],
                purpose: ["read"],
                title: 'Interest',
                translateKey: 'nav.appsHomes.interest',
                icon: 'interest',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [SUPER_ADMIN,ADMIN],
                subMenu: [
                    {
                        key: 'interest.interest',
                        menu_id: ["32"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/interests/interest-list`,
                        title: 'Interest',
                        translateKey: 'nav.interest.interest-list',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'interest.interest-create',
                        menu_id: ["32"],
                        purpose: ["create"],
                        path: `${APP_PREFIX_PATH}/interests/interest-new`,
                        title: 'Create Interest',
                        translateKey: 'nav.interest.interest-create',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'homes.movie-request',
                path: '',
                menu_id: ["56"],
                purpose: ["read"],
                title: 'Movie Request',
                translateKey: 'nav.appsHomes.movie-request',
                icon: 'movieRequest',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [SUPER_ADMIN,ADMIN],
                subMenu: [
                    {
                        key: 'interest.movie-request',
                        menu_id: ["56"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/movie-request/movie-request-list`,
                        title: 'Movie Request',
                        translateKey: 'nav.movie-request.movie-request-list',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN],
                        subMenu: [],
                    }
                ],
            },
            {
                key: 'homes.contact',
                path: '',
                menu_id: ["57"],
                purpose: ["read"],
                title: 'Contacts',
                translateKey: 'nav.appsHomes.contact',
                icon: 'contact',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [SUPER_ADMIN,ADMIN],
                subMenu: [
                    {
                        key: 'contact.contact',
                        menu_id: ["57"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/contacts/contact-list`,
                        title: 'Contacts List',
                        translateKey: 'nav.contact.contact-list',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN],
                        subMenu: [],
                    }
                ],
            },



            {
                key: 'homes.fcm',
                path: '',
                menu_id: ["5"],
                purpose: ["read"],
                title: 'Push Notification',
                translateKey: 'nav.appsHomes.push-notification',
                icon: 'notification',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [SUPER_ADMIN,ADMIN,MANAGER],
                subMenu: [
                    {
                        key: 'fcm.fcm',
                        menu_id: ["5"],
                        purpose: ["read"],
                        path: `${APP_PREFIX_PATH}/fcm/notification-list`,
                        title: 'Notification',
                        translateKey: 'nav.fcm.notification-list',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN,MANAGER],
                        subMenu: [],
                    },
                    {
                        key: 'fcm.fcm-create',
                        menu_id: ["5"],
                        purpose: ["create"],
                        path: `${APP_PREFIX_PATH}/fcm/notification-new`,
                        title: 'Create Notification',
                        translateKey: 'nav.fcm.notification-create',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [SUPER_ADMIN,ADMIN,MANAGER],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default appsNavigationConfig
